FROM amazoncorretto:17-alpine-jdk
MAINTAINER Fabiola_Romano
copy target/FabiolaRomano-0.0.1-SNAPSHOT.jar FabiolaRomano-0.0.1-SNAPSHOT.jar
entrypoint ["java","-jar","/FabiolaRomano-0.0.1-SNAPSHOT.jar"]


